feat: try release to github

diff --git a/pipelines/managed/release-to-github/release-to-github.yaml b/pipelines/managed/release-to-github/release-to-github.yaml
--- a/pipelines/managed/release-to-github/release-to-github.yaml
+++ b/pipelines/managed/release-to-github/release-to-github.yaml
@@ -15,23 +15,25 @@ spec:
   params:
     - name: release
       type: string
-      description:
-        The namespaced name (namespace/name) of the Release custom resource initiating this pipeline execution
+      description: The namespaced name (namespace/name) of the Release custom resource initiating this pipeline execution
     - name: releasePlan
       type: string
       description: The namespaced name (namespace/name) of the releasePlan
     - name: releasePlanAdmission
       type: string
       description: The namespaced name (namespace/name) of the releasePlanAdmission
+      default: ""
     - name: releaseServiceConfig
       type: string
       description: The namespaced name (namespace/name) of the releaseServiceConfig
+      default: release-service/release-service-config
     - name: snapshot
       type: string
       description: The namespaced name (namespace/name) of the snapshot
     - name: enterpriseContractPolicy
       type: string
       description: JSON representation of the EnterpriseContractPolicy
+      default: '{"description":"Red Hat''s enterprise requirements","sources":[{"name":"Default","policy":["github.com/enterprise-contract/ec-policies//policy/lib","github.com/enterprise-contract/ec-policies//policy/release"],"data":["oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest","github.com/release-engineering/rhtap-ec-policy//data"]}],"configuration":{"exclude":["step_image_registries","tasks.required_tasks_found:prefetch-dependencies"],"include":["@slsa3"]},"publicKey":"k8s://openshift-pipelines/public-key"}'
     - name: enterpriseContractExtraRuleData
       type: string
       description: |
@@ -46,12 +48,12 @@ spec:
       type: string
       description: Cleans up workspace after finishing executing the pipeline
       default: "true"
-    - name: verify_ec_task_bundle
-      type: string
-      description: The location of the bundle containing the verify-enterprise-contract task
-    - name: verify_ec_task_git_revision
-      type: string
-      description: The git revision to be used when consuming the verify-conforma task
+    # - name: verify_ec_task_bundle
+    #   type: string
+    #   description: The location of the bundle containing the verify-enterprise-contract task
+    # - name: verify_ec_task_git_revision
+    #   type: string
+    #   description: The git revision to be used when consuming the verify-conforma task
     - name: taskGitUrl
       type: string
       description: The url to the git repo where the release-service-catalog tasks to be used are stored
@@ -117,6 +119,30 @@ spec:
           workspace: release-workspace
       runAfter:
         - verify-access-to-resources
+    - name: debug-collect-data-output
+      taskSpec:
+        workspaces:
+          - name: data
+        steps:
+          - name: list-files
+            image: alpine
+            script: |
+              echo "Listing files in workspace:"
+              ls -l $(workspaces.data.path)
+              echo "---"
+
+              echo "Showing content of snapshotSpec file:"
+              cat $(workspaces.data.path)/$(tasks.collect-data.results.snapshotSpec) || echo "File not found"
+
+              echo "---"
+
+              echo "Dump of task results:"
+              echo "snapshotSpec=$(tasks.collect-data.results.snapshotSpec)"
+      workspaces:
+        - name: data
+          workspace: release-workspace
+      runAfter:
+        - collect-data
     - name: check-data-keys
       params:
         - name: dataPath
@@ -163,36 +189,36 @@ spec:
           workspace: release-workspace
       runAfter:
         - collect-data
-    - name: verify-enterprise-contract
-      taskRef:
-        resolver: "bundles"
-        params:
-          - name: bundle
-            value: $(params.verify_ec_task_bundle)
-          - name: kind
-            value: task
-          - name: name
-            value: verify-enterprise-contract
-      params:
-        - name: IMAGES
-          value: "$(workspaces.data.path)/$(tasks.collect-data.results.snapshotSpec)"
-        - name: SSL_CERT_DIR
-          value: /var/run/secrets/kubernetes.io/serviceaccount
-        - name: POLICY_CONFIGURATION
-          value: $(params.enterpriseContractPolicy)
-        - name: STRICT
-          value: "1"
-        - name: IGNORE_REKOR
-          value: "true"
-        - name: EXTRA_RULE_DATA
-          value: $(params.enterpriseContractExtraRuleData)
-        - name: TIMEOUT
-          value: $(params.enterpriseContractTimeout)
-      workspaces:
-        - name: data
-          workspace: release-workspace
-      runAfter:
-        - validate-single-component
+    # - name: verify-enterprise-contract
+    #   taskRef:
+    #     resolver: "bundles"
+    #     params:
+    #       - name: bundle
+    #         value: $(params.verify_ec_task_bundle)
+    #       - name: kind
+    #         value: task
+    #       - name: name
+    #         value: verify-enterprise-contract
+    #   params:
+    #     - name: IMAGES
+    #       value: "$(workspaces.data.path)/$(tasks.collect-data.results.snapshotSpec)"
+    #     - name: SSL_CERT_DIR
+    #       value: /var/run/secrets/kubernetes.io/serviceaccount
+    #     - name: POLICY_CONFIGURATION
+    #       value: $(params.enterpriseContractPolicy)
+    #     - name: STRICT
+    #       value: "1"
+    #     - name: IGNORE_REKOR
+    #       value: "true"
+    #     - name: EXTRA_RULE_DATA
+    #       value: $(params.enterpriseContractExtraRuleData)
+    #     - name: TIMEOUT
+    #       value: $(params.enterpriseContractTimeout)
+    #   workspaces:
+    #     - name: data
+    #       workspace: release-workspace
+    #   runAfter:
+    #     - validate-single-component
     - name: extract-requester-from-release
       taskRef:
         resolver: "git"
@@ -220,7 +246,6 @@ spec:
             if [[ ${AUTHOR} == "" ]] ; then exit 1 ; fi
       runAfter:
         - verify-access-to-resources
-        - verify-enterprise-contract
     - name: extract-binaries-from-image
       workspaces:
         - name: data
@@ -259,37 +284,37 @@ spec:
           value: $(tasks.extract-binaries-from-image.results.binaries_path)
       runAfter:
         - extract-binaries-from-image
-    - name: sign-base64-blob
-      workspaces:
-        - name: data
-          workspace: release-workspace
-      taskRef:
-        resolver: "git"
-        params:
-          - name: url
-            value: $(params.taskGitUrl)
-          - name: revision
-            value: $(params.taskGitRevision)
-          - name: pathInRepo
-            value: tasks/managed/sign-base64-blob/sign-base64-blob.yaml
-      params:
-        - name: dataPath
-          value: $(tasks.collect-data.results.data)
-        - name: blob
-          value: $(tasks.base64-encode-checksum.results.blob)
-        - name: requester
-          value: $(tasks.extract-requester-from-release.results.output-result)
-        - name: binariesPath
-          value: $(tasks.extract-binaries-from-image.results.binaries_path)
-        - name: pipelineRunUid
-          value: $(context.pipelineRun.uid)
-        - name: taskGitUrl
-          value: "$(params.taskGitUrl)"
-        - name: taskGitRevision
-          value: "$(params.taskGitRevision)"
-      runAfter:
-        - base64-encode-checksum
-        - extract-requester-from-release
+    # - name: sign-base64-blob
+    #   workspaces:
+    #     - name: data
+    #       workspace: release-workspace
+    #   taskRef:
+    #     resolver: "git"
+    #     params:
+    #       - name: url
+    #         value: $(params.taskGitUrl)
+    #       - name: revision
+    #         value: $(params.taskGitRevision)
+    #       - name: pathInRepo
+    #         value: tasks/managed/sign-base64-blob/sign-base64-blob.yaml
+    #   params:
+    #     - name: dataPath
+    #       value: $(tasks.collect-data.results.data)
+    #     - name: blob
+    #       value: $(tasks.base64-encode-checksum.results.blob)
+    #     - name: requester
+    #       value: $(tasks.extract-requester-from-release.results.output-result)
+    #     - name: binariesPath
+    #       value: $(tasks.extract-binaries-from-image.results.binaries_path)
+    #     - name: pipelineRunUid
+    #       value: $(context.pipelineRun.uid)
+    #     - name: taskGitUrl
+    #       value: "$(params.taskGitUrl)"
+    #     - name: taskGitRevision
+    #       value: "$(params.taskGitRevision)"
+    #   runAfter:
+    #     - base64-encode-checksum
+    #     - extract-requester-from-release
     - name: collect-gh-params
       workspaces:
         - name: data
@@ -338,7 +363,7 @@ spec:
           value: $(tasks.collect-data.results.resultsDir)
       runAfter:
         - collect-gh-params
-        - sign-base64-blob
+        # - sign-base64-blob
     - name: update-cr-status
       params:
         - name: resource
diff --git a/tasks/managed/create-github-release/create-github-release.yaml b/tasks/managed/create-github-release/create-github-release.yaml
--- a/tasks/managed/create-github-release/create-github-release.yaml
+++ b/tasks/managed/create-github-release/create-github-release.yaml
@@ -41,20 +41,51 @@ spec:
         #!/usr/bin/env bash
         set -ex
 
+        echo "HERE"
+
         RESULTS_FILE="$(workspaces.data.path)/$(params.resultsDirPath)/create-github-release-results.json"
+        echo "RESULTS_FILE: ${RESULTS_FILE}"
 
         cd "$(workspaces.data.path)/$CONTENT_DIRECTORY"
         set -o pipefail
-        shopt -s failglob
+        # shopt -s failglob
+        shopt -u failglob
 
         OWNER_REPO=${REPOSITORY#https://github.com/}
+        echo "OWNER_REPO: ${OWNER_REPO}"
         RELEASE="$(gh api "repos/${OWNER_REPO}/releases" --jq ".[] | select(.tag_name == \"v${RELEASE_VERSION}\")")"
+        echo "RELEASE: ${RELEASE}"
+
+
+        # files=(./*.zip ./*.json ./*SHA256SUMS ./*.sig)
+        # found_files=()
+
+        # for f in "${files[@]}"; do
+        #   # check if any file matches the glob (nullglob helps here)
+        #   matches=( $f )
+        #   if [ ${#matches[@]} -gt 0 ]; then
+        #     found_files+=("${matches[@]}")
+        #   fi
+        # done
+
+        shopt -s nullglob
+        found_files=(./*.zip ./*.json ./*SHA256SUMS ./*.sig)
+        shopt -u nullglob
+
+        if [ ${#found_files[@]} -eq 0 ]; then
+          echo "No release files found in $CONTENT_DIRECTORY"
+          # exit 1
+        fi
+
         if [ -n "$RELEASE" ]; then
           echo "Release v${RELEASE_VERSION} exists"
           echo "$REPOSITORY/releases/tag/v${RELEASE_VERSION}" > "$(results.url.path)"
         else
-          gh release create "v${RELEASE_VERSION}" ./*.zip ./*.json ./*SHA256SUMS ./*.sig \
-          --repo "$REPOSITORY" --title "Release $RELEASE_VERSION" | tee "$(results.url.path)"
+          ls -l
+          # gh release create "v${RELEASE_VERSION}" ./*.zip ./*.json ./*SHA256SUMS ./*.sig \
+          # --repo "$REPOSITORY" --title "Release $RELEASE_VERSION" | tee "$(results.url.path)"
+          gh release create "v${RELEASE_VERSION}" "${found_files[@]}" \
+            --repo "$REPOSITORY" --title "Release $RELEASE_VERSION" | tee "$(results.url.path)"
         fi
 
         jq -n --arg release "$(cat "$(results.url.path)")" '{"github-release": {"url": $release}}' | tee "$RESULTS_FILE"
